### ISSUE TITLE
Enable Azure pipelines or github actions

### ISSUE THREAD

**Issue by TysonAndre** [igbinary/igbinary#302]
@phadej @tricky 

A minimal configuration is already checked in - this will probably be rewritten to use dockerized nts/zts images to have the same test coverage as the current travis. However, because I'm a member of this repo and not an owner (https://github.com/orgs/igbinary/people), I'm not able to authorize the Azure Pipelines application or change any other settings.

Travis CI open source builds are encountering hours-long backlogs at some times of day (for the last month), and having quick feedback is useful when creating/reviewing PRs. (https://www.traviscistatus.com/)

https://github.com/php/php-src/blob/master/azure-pipelines.yml azure is currently also used by php-src itself

1. https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started/pipelines-sign-up?view=azure-devops has the tutorial for creating an account
    https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=java%2Ctfs-2018-2%2Cbrowser has the basic tutorial for setting up a pipeline
2. Alternately, I could set this up if promoted to an owner of this repo

**Comment by phadej** [comment]
Are Azure Pipelines considerably different (better?) then GitHub Actions? Latter won't  require any extra accounts.

**Comment by dktapps** [comment]
Azure Pipelines and GitHub Actions use the same backend as far as I understand. They at least share the same images.

**Comment by TysonAndre** [comment]
https://github.community/t/templates-for-github-actions/18045 - it seems like templates aren't supported in github actions, which would be inconvenient for the large matrix of version/setting combinations currently tested in travis.

Other than that, they seem similar and I haven't used GitHub Actions before

**Comment by TysonAndre** [comment]
https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs seems to support some sort of matrix for build settings

**Comment by TysonAndre** [comment]
I started looking at github actions for another project.

Once I figured it out, it looked remarkably straightforward, e.g. ubuntu has docker pre-installed, and sudo in a docker build worked properly (unlike azure pipelines)

So once one writes a script to docker build and/or docker run that can be reused in github workflows. I imagine `FROM php:$PHP_VERSION` could be used with a dockerfile template (e.g. use sed to replace PHP_VERSION before running docker)

`.github/workflows/main.yml`


```yml
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-environment-variables-in-a-matrix
    strategy:
      matrix:
       include:
         - PHP_VERSION: 7.0
         - PHP_VERSION: 8.0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build and test in docker
        run: bash ./test_in_docker.sh ${{ matrix.PHP_VERSION }}
```


It seems as though I should have the permissions to enable github actions
